### ISSUE TITLE
add in comment ignoring for CSS

### ISSUE THREAD

**Issue by Pomax** [mozilla/slowparse#12]
block comments are not ignored at the moment, and they should very much be.

**Comment by toolness** [comment]
If you could also add the comment's text extents to the `parseInfo` blob, that would be swell. In the future, this would allow us to easily e.g. point out a comment in a [tutorial](http://toolness.github.com/webmaking-tutorial-prototype/).

**Comment by Pomax** [comment]
hmm, I'm making the CSS parser return a single object for the parserInfo of the <style> element, since nothing inside of it counts as more than plain text content as far as the DOM is concerned. Would we rewrite the comments as dom comment nodes?

**Comment by toolness** [comment]
Well, in 81684b70f5978058c76b195f407c6f40d66e6f20 I extended the `parseInfo` blob it returns to actually include a bunch of information about the CSS contained within... I was originally thinking of actually putting this on top of the [CSSStyleSheet](https://developer.mozilla.org/en/DOM/CSSStyleSheet) DOM in the `sheet` property of the `<style>` node but decided against it, partly because that `sheet` property is only non-null when the `<style>` element is added to a real document.

Anyways, since `parseInfo.rules` is an array of rules in the sheet, maybe `parseInfo.comments` can be an array of comments in it?

**Comment by Pomax** [comment]
done and done, pull request #17 pending.
