### ISSUE TITLE
gh-pages front end

### ISSUE THREAD

**Issue by humphd** [mozilla/slowparse#13]
With a view to making more of a community around slowparse, it might be nice to have a very simple jshint style web page that uses it, and people can try without having to do any setup.  One logical way to do this would be to create a gh-pages branch that gets updated via post commit hook.  Then we can always have a testable version of the tool online.

**Comment by Pomax** [comment]
we only have a gh-pages branch, but there's no index.html in the main dir, only in the test and demo dirs. We can set up a simpler version of the demo page in the main dir, though?

**Comment by humphd** [comment]
Sure, and what's in gh-pages doesn't have to match in any way what's in master.

**Comment by toolness** [comment]
Hmm, I personally am constantly confused by branches that are not true "branches" but rather separate mini-projects... It especially gets confusing to me when different branches share similar files that need to be constantly synced with each other via commit hooks, as we'd have to do w/ slowparse.js. I think it triggers the same "whoa" effect that happens when I read really recursive code.

Personally, I'd rather have a "docs" directory in the main branch that we publish out to a separate, non-github-hosted website via a commit hook, possibly with an intermediate build step... but I can be convinced to do the more confusing and pseudo-recursive thing. :)

BTW, until we figure this out I am just keeping the main docs in the README.md. The one "build step" we (regrettably) have right now is the docco docs, which I'm manually regenerating, pushing [here](http://labs.toolness.com/temp/slowparse/docs/slowparse.html) and linking to from the readme.
