### ISSUE TITLE
<p> text <p> text does not signal a new paragraph, but a nested element

### ISSUE THREAD

**Issue by Pomax** [mozilla/slowparse#14]
annoying HTML thing, we may or may not want to support this.

**Comment by toolness** [comment]
Glargh I really despise this feature of HTML.

I can see us needing to support this if we bust up the scraping of sites in the wild and make it possible to edit them using a slowparse-enabled editor, but right now even I avoid the heck out of HTML like that because I have no idea what a browser will make of it. It totally breaks my mental model of how I am supposed to talk to a machine with HTML... But maybe I am a noob that way. :P

**Comment by Pomax** [comment]
more complicated than I had hoped due to how we parse HTML so I'm parking this code here for the moment

```
// The following 13 elements are elements that may or may not have an
// explicit closing tag. Leaving it off is not erroneous. Specified in:
//  http://dev.w3.org/html5/html-author/#index-of-elements
optionallyClosableHtmlElements: ["colgroup", "dd", "dt", "li", "optgroup",
                                 "option", "p", "tbody", "td", "tfoot",
                                 "th", "thead", "tr"],
...
// This is a helper function to determine whether a given tag
// MUST, or MAY have a closing element. We use this to determine
// whether a missing closing tag is an error or not.
_knownOptionallyClosableHtmlElements: function(tagname) {
  return this.optionallyClosableHtmlElements.indexOf(tagname) > -1;
},
```

In order to make this work, we also need to know which elements trigger an auto-close so that we can finalise the DOMBuilder.currentnode

**Comment by Pomax** [comment]
The exact rules for these elements are described in http://www.w3.org/TR/2010/WD-html5-20100624/syntax.html#optional-tags
