### ISSUE TITLE
allow /> for html4/xhtml documents (with possible html5 warning) 

### ISSUE THREAD

**Issue by Pomax** [mozilla/slowparse#30]
we should not fatally break on older html closers, rather we should allow it and warn or notify

**Comment by toolness** [comment]
This was fixed in 83034bf52ee971e814ce169df47c1e20e6d9d795.

Note that we do _not_ allow `/>` for non-void elements, because the results of this are actually completely unintuitive--you'd think that a browser would see it and self-close the element, as XHTML does, but it actually just throws out the `/`, interpreting it as an _opening_ tag but not closing it. I once spent hours debugging some HTML I wrote because the result was so counterintuitive.
