### ISSUE TITLE
Missing semi colons in CSS should cause an error

### ISSUE THREAD

**Issue by SomeHats** [mozilla/slowparse#58]
``` html
<style>
  body {
    color: red
    font-size: 16px
  }
</style>
```

The code above in incorrect (missing semi colons), but Slowparse doesn't report an error. For reference, the Firefox Dev Tools give the following error:

```
Expected end of value but found 'font-size'.  Error in parsing value for 'color'.  Declaration dropped. @ http://mozilla.github.io/slowparse/demo/:4
```

**Comment by Pomax** [comment]
this is only possible if we also put in full awareness of "allowed values for each property", as there is no syntactic difference between "color: red\nfont-size" and "border: 1px\n solid black". That said, there should be an error on that second colon, because that breaks the permitted pattern, which is definitely a bug.
