### ISSUE TITLE
A message that could be improved with misordered closed tags

### ISSUE THREAD

**Issue by pamelafox** [mozilla/slowparse#67]
This HTML:

```
<strong><em>Nobody’s born smart. We all start at 0. Can’t talk, can’t walk, certainly can’t do algebra.<br>
        You can learn anything.</strong></em>
```

results in error:
"The closing </strong> tag here doesn't pair with the opening <em> tag here. This is likely due to a missing </em> tag."

It'd be better if it realized it's a mis-ordering issue, like "This is likely due to misordering the </em> and </strong> tags".
This was another one where it took me a bit myself to realize the problem, especially as browsers are pretty forgiving of that sort of thing.

Not sure if it's possible to detect the mis-ordering however.

**Comment by Pomax** [comment]
Slowparse won't know there's a misordering, since the error is thrown when it walks over `</strong`, then terminates with the wrong-tag error (so it'll  never see anything that comes after that). We could change the text to _This is likely due to a missing or misordered tag_

**Comment by Pomax** [comment]
I've changed the phrasing in https://github.com/mozilla/slowparse/commit/3564da815786f7fc42cdf9ed9a06ad35f8ecfac5, note that the localised strings are now explicitly bundled with the Slowparse project, so you can either keep using 1.0.x and update your string files accordingly, or you can switch to using the bundled locale file (little bit more work, but probably worth it since that means updating slowparse with new errors simply pulls in the human-readable errors alongwith)
