### ISSUE TITLE
Not capturing text nodes in optional-and-ommitted tags

### ISSUE THREAD

**Issue by lemiant** [mozilla/slowparse#70]
If I parse code with a `<li>` that omits its closing tag it is closed prematurely:

```
<ul>
    <li>Hello Everyone
</ul>
```

becomes

```
<ul>
    <li></li>Hello Everyone
</ul>
```

**Comment by Pomax** [comment]
that's actually entirely valid HTML (the `</li>` is optional for instances like the example you gave). When you say it "becomes" the second code, can you elaborate on that? Do you mean the DOM structure that Slowparse has built and returns when you perform a validation run? (It is not recommended that you use that result: if slowparse does not find any errors in the input, you should use that input since it should be safe, rather than the output that slowparse generates while walking the input string)

**Comment by lemiant** [comment]
Sorry, I guess that wasn't particularly clear. I mean that although the correct parsing of the above HTML would be an li tag with the text node inside it, instead slow parse creates an li tag followed by a text node.

**Comment by Pomax** [comment]
yes, so my question is "are you using the DOM that slowparse ends up building?", because if so that is not recommended, instead just inject the same source you'r passing into Slowparse for validation.

It's still kind of a bug that the validation DOM isn't building the textnode correctly, but you should not be using slowparse's DOM output as if it's sanitized data for injection, because it very much isn't. In fact, there is no guarantee that the DOM slowparse builds is actually identical. Ideally it is, but even when it's not its primary role is to aid error detection, not be a sanitized "proper" DOM.

**Comment by lemiant** [comment]
That is the case. We will try switching over to using a DOM parsed by the browser. Thanks for your help.

**Comment by Pomax** [comment]
I will try to amend the README to make this explicit. I'll close this issue and file a new one to see whether the DOM built still reflects correct parsing or not (if so we won't be touching it, but if it's actually getting things wrong as a consequence, that'll need fixing)
